### ISSUE TITLE
Support Rails 4

### ISSUE THREAD

**Issue by kidwm** [JohnColvin/jquery-scrollto-rails#6]
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jquery-scrollto-rails (>= 0) ruby depends on
      railties (~> 3.1) ruby

```
sass-rails (~> 4.0.0) ruby depends on
  railties (4.0.0)
```

**Comment by alessandro-molari** [comment]
Any news?

**Comment by JohnColvin** [comment]
It should accept rails 4. Support was added by https://github.com/JohnColvin/jquery-scrollto-rails/pull/5.

Can you point me to a repo that has this issue or submit a PR that addresses it?

**Comment by kidwm** [comment]
It works now, Thanks!
